server:
  port: 8084

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    serialization:
      indent_output: true

app:
  rabbitmq:
    queue:
      project-created: project.created.queue
      project-member-added: project.member.added.queue
      invite: email.invite.queue
      member-added: email.member.added.queue
      role-updated: email.member.role.updated.queue
      member-removed: email.member.removed.queue
      new-lead-assigned: project.new.lead.assigned.queue
    exchange:
      events: events.exchange
      project: project.exchange